### PR TITLE
Fixes the chat sidebar UI and changed the navbar color to blue

### LINKED ISSUE #3: Set up basic styling
Apply general styling using Tailwind CSS

### LINKED ISSUE #6: Make messaging page UI
Create UI for messaging page with a place to select different users you're chatting with as well as a way to view and send messages

### PR DESCRIPTION
**Pull request by StephenKhoaUmass**
Fixed #6 
Fixed #3

### CODE REVIEW

File: front-end/src/components/messaging/ChatMessages.tsx [hunk 1]
```diff
@@ -0,0 +1,129 @@
...
+  //     <div className="w-full h-full flex items-center justify-center bg-gray-50">
+  //       <div className="text-center max-w-md p-6">
+  //         <h2 className="text-2xl font-bold text-gray-800 mb-2">Start a conversation</h2>
+  //         <p className="text-gray-600">
+  //           Select a conversation from the sidebar or start a new one to connect with workout partners.
+  //         </p>
+  //       </div>
+  //     </div>
+  //   )
+  // }
```
Comment (sagarikasonni) [inline front-end/src/components/messaging/ChatMessages.tsx:49]: Maybe delete this later

**Review by sagarikasonni — APPROVED** [review]
